#!/usr/bin/env bash

CMD="git --no-pager log"
EMAIL=$(git config user.email)
OPTS="--all --no-merges --first-parent --reverse --committer=$EMAIL"
ONE_NEWLINE="--max-count=1 --pretty=format:%n"
RANGE_LONG="1 week"
RANGE_MEDIUM="yesterday midnight"
RANGE_SHORT="midnight"

# padding on top
$CMD $OPTS \
    --since="$RANGE_LONG" \
    --until="$RANGE_MEDIUM" \
    $ONE_NEWLINE

# last week
$CMD $OPTS \
    --since="$RANGE_LONG" \
    --until="$RANGE_MEDIUM" \
    --pretty=format:"%C(yellow)%>(14)%cr%Creset - %s%C(bold blue)%d%Creset"

# newline
$CMD $OPTS \
    --since="$RANGE_MEDIUM" \
    --until="$RANGE_SHORT" \
    $ONE_NEWLINE

# last 24 hours
$CMD $OPTS \
    --since="$RANGE_MEDIUM" \
    --until="$RANGE_SHORT" \
    --pretty=format:"%C(bold yellow)%>(14)%cr%Creset - %s%C(bold blue)%d%Creset"

# newline
$CMD $OPTS \
    --since="$RANGE_SHORT" \
    $ONE_NEWLINE

# last 24 hours
$CMD $OPTS \
    --since="$RANGE_SHORT" \
    --pretty=format:"%C(bold green)%>(14)%cr%Creset - %s%C(bold blue)%d%Creset"

# padding on bottom
echo ""
echo ""
